### ISSUE TITLE
Need some help on Crucible for FHIR Tests

### ISSUE THREAD

**Issue by revathysreenath** [fhir-crucible/fhir_dstu2#1]
Hi All,

I am trying to use Crucible to determine the compliance to FHIR specifications by executing the predefined FHIR Tests.When i try to run the tests , it is executing indefinitely. Can anyone please help me with this. I am unable to find good documentation on using this tool.

Also can anyone please help me with following information :
1. Should the FHIR server which I am using be a public server to run these tests?
2. Is it possible for me to download the tests and tool and run it locally?
3. Is supporting software conformance resource mandatory for the tool to be used?

Thanks,
Revathy

**Comment by jawalonoski** [comment]
Hi Revathy,
1. Yes, the FHIR server under test must be publicly accessible if you are testing from projectcrucible.org. If you setup the system locally (see https://github.com/fhir-crucible/crucible/blob/master/README.md) in your own intranet, then the server under test needs to be accessible to your local system.
2. Yes, you can use fhir-crucible/plan_executor to run the tests locally (from the command line) if you are familiar with Ruby.
3. From projectcrucible.org, if you enter a server URL, and click 'Begin', it will load a page where you can select the tests. If the conformance statement is not available, you can still select tests and click the 'Loading' button (despite the spinning icon) and the tests will start to execute.

Hope that helps.

Jay.
